Repository kubernetes-sigs/cluster-proportional-autoscaler, pull requests merged in 2018-07, with the labels that each got.

#46 Watch nodes instead listing
  Godeps/Godeps.json
  pkg/autoscaler/k8sclient/k8sclient.go
  vendor/k8s.io/apimachinery/pkg/util/diff/diff.go
  vendor/k8s.io/apimachinery/pkg/util/diff/diff_test.go
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/controller_test.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo_test.go
  vendor/k8s.io/client-go/tools/cache/doc.go
  vendor/k8s.io/client-go/tools/cache/expiration_cache.go
  vendor/k8s.io/client-go/tools/cache/expiration_cache_fakes.go
  vendor/k8s.io/client-go/tools/cache/expiration_cache_test.go
  vendor/k8s.io/client-go/tools/cache/fake_custom_store.go
  vendor/k8s.io/client-go/tools/cache/fifo.go
  vendor/k8s.io/client-go/tools/cache/fifo_test.go
  vendor/k8s.io/client-go/tools/cache/index.go
  vendor/k8s.io/client-go/tools/cache/index_test.go
  vendor/k8s.io/client-go/tools/cache/listers.go
  vendor/k8s.io/client-go/tools/cache/listwatch.go
  vendor/k8s.io/client-go/tools/cache/mutation_detector.go
  vendor/k8s.io/client-go/tools/cache/mutation_detector_test.go
  vendor/k8s.io/client-go/tools/cache/processor_listener_test.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/cache/reflector_test.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/tools/cache/shared_informer_test.go
  vendor/k8s.io/client-go/tools/cache/store.go
  vendor/k8s.io/client-go/tools/cache/store_test.go
  vendor/k8s.io/client-go/tools/cache/testing/fake_controller_source.go
  vendor/k8s.io/client-go/tools/cache/testing/fake_controller_source_test.go
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/client-go/tools/cache/undelta_store.go
  vendor/k8s.io/client-go/tools/cache/undelta_store_test.go
Labels: cncf-cla: yes, lgtm, size/XXL

#47 Release cluster-proportional-autoscaler 1.2.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/XS

#48 Fix the API version for new release
  README.md
  examples/RBAC/RBAC-configs.yaml
  examples/README.md
  examples/ladder-defaultparams.yaml
  examples/ladder.yaml
  examples/linear-defaultparams.yaml
  examples/linear.yaml
Labels: cncf-cla: yes, lgtm, size/S

#50 update rbac to allow cluster-proportional-autoscaler watch nodes
  examples/RBAC/RBAC-configs.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#49 Change container registry to staging
  Makefile
Labels: cncf-cla: yes, size/XS
