Repository kubernetes-sigs/cluster-proportional-autoscaler, pull requests merged in 2020-04, with the labels that each got.

#75 Add simple healthz
  README.md
  cmd/cluster-proportional-autoscaler/options/options.go
  pkg/autoscaler/autoscaler_server.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/health.go
  pkg/autoscaler/k8sclient/mock_k8sclient.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#79 use node.Status.Allocatable when calculate cores
  pkg/autoscaler/k8sclient/k8sclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#81 Add includeUnschedulableNodes option to linear controller
  README.md
  examples/linear-defaultparams.yaml
  pkg/autoscaler/controller/linearcontroller/linear_controller.go
  pkg/autoscaler/controller/linearcontroller/linear_controller_test.go
  pkg/autoscaler/k8sclient/k8sclient.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#72 Allow ladder to support setting replicas to 0
  README.md
  pkg/autoscaler/controller/laddercontroller/ladder_controller.go
  pkg/autoscaler/controller/laddercontroller/ladder_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
